### PR TITLE
Added candidate flag to metalsmith command

### PR DESCRIPTION
**Pull request by skanthed**

### CODE REVIEW

**Comment by tzumainn** [comment]
Looks good! One minor comment; there's no need for hyphens in the subject of the PR. I'd remove them to make it more readable.

**Review by DanNiESh — APPROVED** [review]
LGTM

**Comment by tzumainn** [comment]
Can you also update the ``metalsmith deploy`` example in https://esi.readthedocs.io/en/latest/usage/cli.html#provisioning-a-node?

**Comment by skanthed** [comment]
@tzumainn  I have updated that in other PR. Where I have added metalsmith undeploy command.

**Comment by skanthed** [comment]
@tzumainn Eariler I made that change in other PR, removed the change from other PR and added it here to cli.rst file.

**Comment by tzumainn** [comment]
Thanks! I think just replace node-uuid with node-id since both the UUID and name work

**Comment by DanNiESh** [comment]
Oh, one last thing, this branch is 6 commits behind master, you might need to sync it before merge into master.

**Comment by skanthed** [comment]
I have closed this and created another PR to resolve conflicts.  https://github.com/CCI-MOC/esi/pull/384

**Pull request closed without merging**
